# Generated by Django 3.2.6 on 2023-10-12 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_data_analysis_name', models.CharField(max_length=200, verbose_name='name')),
                ('tb_data_analysis_date', models.DateTimeField(default=datetime.datetime(2010, 1, 1, 1, 1, 1, 342380), verbose_name='query date')),
                ('tb_data_analysis_username', models.CharField(default='guest', max_length=200, verbose_name='user name')),
                ('tb_data_analysis_mh01', models.CharField(max_length=200, verbose_name='How many relative')),
                ('tb_data_analysis_mh02', models.CharField(max_length=200, verbose_name='Bowel disease')),
                ('tb_data_analysis_mh03', models.CharField(max_length=200, verbose_name='Diabetes')),
                ('tb_data_analysis_bf01', models.CharField(max_length=200, verbose_name='Alcohol')),
                ('tb_data_analysis_bf02', models.CharField(max_length=200, verbose_name='Obesity')),
                ('tb_data_analysis_bf03', models.CharField(max_length=200, verbose_name='Red Meat')),
                ('tb_data_analysis_bf04', models.CharField(max_length=200, verbose_name='Meat Consumption')),
                ('tb_data_analysis_bf05', models.CharField(max_length=200, verbose_name='Smoke')),
                ('tb_data_analysis_fd01', models.CharField(default='fd_01_default', max_length=200, verbose_name='Physical Activity')),
                ('tb_data_analysis_fd02', models.CharField(default='fd_01_default', max_length=200, verbose_name='Dairy Consumption')),
                ('tb_data_analysis_fd03', models.CharField(default='fd_01_default', max_length=200, verbose_name='Milk Consumption')),
            ],
            options={
                'verbose_name': 'Data_Analysis',
                'verbose_name_plural': 'Data_Analysis',
                'db_table': 'tb_data_analysis',
            },
        ),
    ]
